general:
  buildTool: "mta"

stages:
  Build:
    mtaBuild: true

  Release:
    cloudFoundryDeploy: true

steps:
  cloudFoundryDeploy:
    cfCredentialsId: "cf-token"
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "3d1a9f0ftrial"
    cfSpace: "dev"