general:
  buildTool: "mta"
  deployTool: "cf"

stages:
  Build:
    mtaBuild: true

  Deploy:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "3d1a9f0ftrial"
    cfSpace: "dev"
    cfCredentialsId: "btpdeploy"